export type VillageRecord = {
  id: number;
  nameTr: string;
  nameKu: string;
  belde: string | null;
};

/** Eleşkirt köyleri (Türkçe / Kürtçe). Tahir beldesine bağlı köyler `belde: "Tahir"`. */
export const villages: VillageRecord[] = [
  { id: 1, nameTr: "Abdiköy", nameKu: "Evdê", belde: null },
  { id: 2, nameTr: "Akyumak", nameKu: "Avxarik", belde: null },
  { id: 3, nameTr: "Alagün", nameKu: "Asêb", belde: null },
  { id: 4, nameTr: "Alkuşak", nameKu: "Milan", belde: null },
  { id: 5, nameTr: "Arifbey", nameKu: "Arifbeg", belde: null },
  { id: 6, nameTr: "Aşağıkopuz", nameKu: "Qopiza jêrê", belde: null },
  { id: 7, nameTr: "Aydoğdu", nameKu: "Bedir", belde: null },
  { id: 8, nameTr: "Çatalpınar", nameKu: "Sêvik", belde: null },
  { id: 9, nameTr: "Çatkösedağ", nameKu: "Çatkosedax", belde: null },
  { id: 10, nameTr: "Çetinsu", nameKu: "Gelîyan", belde: null },
  { id: 11, nameTr: "Çiftepınar", nameKu: "Çelê", belde: null },
  { id: 12, nameTr: "Dalkılıç", nameKu: "Dalqilîç", belde: null },
  { id: 13, nameTr: "Değirmenoluğu", nameKu: "Şamyan", belde: null },
  { id: 14, nameTr: "Dolutaş", nameKu: "Mardo", belde: null },
  { id: 15, nameTr: "Düzağıl", nameKu: "Aykan", belde: null },
  { id: 16, nameTr: "Düzyayla", nameKu: "Hamzikan", belde: null },
  { id: 17, nameTr: "Ergözü", nameKu: "Tawo", belde: null },
  { id: 18, nameTr: "Goncalı", nameKu: "Xaçûlî", belde: null },
  { id: 19, nameTr: "Gözaydın", nameKu: "Gapira", belde: null },
  { id: 20, nameTr: "Güneykaya", nameKu: "Ebûzeyt", belde: null },
  { id: 21, nameTr: "Güvence", nameKu: "Çilkanîya", belde: null },
  { id: 22, nameTr: "Hasanpınar", nameKu: "Kevrigewrk", belde: null },
  { id: 23, nameTr: "Haydaroğlu", nameKu: "Heyderoxlî", belde: null },
  { id: 24, nameTr: "Hürriyet", nameKu: "Kole", belde: null },
  { id: 25, nameTr: "İkizgeçe", nameKu: "Memitan", belde: null },
  { id: 26, nameTr: "İkizgöl", nameKu: "Alaqîç", belde: null },
  { id: 27, nameTr: "İndere", nameKu: "Rûtan", belde: null },
  { id: 28, nameTr: "Kanatgeren", nameKu: "Bavina jorê", belde: null },
  { id: 29, nameTr: "Kayayolu", nameKu: "Çerkes", belde: null },
  { id: 30, nameTr: "Kokulupınar", nameKu: "Esed-Gomik", belde: null },
  { id: 31, nameTr: "Körpeçayır", nameKu: "Şahnezar", belde: null },
  { id: 32, nameTr: "Mollahüseyin", nameKu: "Mellehiseyn", belde: null },
  { id: 33, nameTr: "Mollasüleyman", nameKu: "Melleslêman", belde: null },
  { id: 34, nameTr: "Oklavalı", nameKu: "Garisyan", belde: null },
  { id: 35, nameTr: "Öztoprak", nameKu: "Erep-Gomaerep", belde: null },
  { id: 36, nameTr: "Palakçayır", nameKu: "Gopal", belde: null },
  { id: 37, nameTr: "Pirabat", nameKu: "Pîrabada", belde: null },
  { id: 38, nameTr: "Ramazan", nameKu: "Remedana", belde: null },
  { id: 39, nameTr: "Sadaklı", nameKu: "Mûsûrya", belde: null },
  { id: 40, nameTr: "Salkımlı", nameKu: "Mollazade", belde: null },
  { id: 41, nameTr: "Söbetaş", nameKu: "Heyşto", belde: null },
  { id: 42, nameTr: "Sultanabat", nameKu: "Siltanabad", belde: null },
  { id: 43, nameTr: "Süzgeçli", nameKu: "Remikan", belde: null },
  { id: 44, nameTr: "Toprakkale", nameKu: "Kelê", belde: null },
  { id: 45, nameTr: "Türkeli", nameKu: "Kurdalya", belde: null },
  { id: 46, nameTr: "Uludal", nameKu: "Bozmezin", belde: null },
  { id: 47, nameTr: "Uzunyazı", nameKu: "Xoşyan", belde: null },
  { id: 48, nameTr: "Yağmurlu", nameKu: "Şêxo", belde: null },
  { id: 49, nameTr: "Yanıkdere", nameKu: "Kirikan", belde: null },
  { id: 50, nameTr: "Yelkesen", nameKu: "Mîrangî", belde: null },
  { id: 51, nameTr: "Yeşilova", nameKu: "Çurûk", belde: null },
  { id: 52, nameTr: "Yığıntaş", nameKu: "Şadîyan", belde: null },
  { id: 53, nameTr: "Yukarıkopuz", nameKu: "Kopiz", belde: null },
  { id: 54, nameTr: "Aşağıcihanbey", nameKu: "Canbegayê xirabe", belde: "Tahir" },
  { id: 55, nameTr: "Aydıntepe", nameKu: "Karpala", belde: "Tahir" },
  { id: 56, nameTr: "Değirmengeçidi", nameKu: "Halyazcilikan", belde: "Tahir" },
  { id: 57, nameTr: "Gökçayır", nameKu: "Kaşkan", belde: "Tahir" },
  { id: 58, nameTr: "Hayrangöl", nameKu: "Heyrangol", belde: "Tahir" },
  { id: 59, nameTr: "Karabacak", nameKu: "Qerebacax", belde: "Tahir" },
  { id: 60, nameTr: "Sarıköy", nameKu: "Sarê", belde: "Tahir" },
];
